spring.application.name=library-backend

spring.datasource.url = jdbc:postgresql://localhost:5432/altis_library_db
spring.datasource.username = postgres
spring.datasource.password = Postgres@2026
spring.jpa.hibernate.ddl-auto = none
spring.flyway.enabled = true

api.security.token.secret=${JWT_SECRET:DuAl5K3zi1eHiBZ-5t404mccn2x5Tdb9E9O5FqpAI9I}

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true