spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.SecurityAutoConfiguration
spring.application.name=library-backend

spring.datasource.url = jdbc:postgresql://localhost:5432/altis_library_db
spring.datasource.username = postgres
spring.datasource.password = Postgres@2026
spring.jpa.hibernate.ddl-auto = update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true